### PR TITLE
Facerecognition v0.6.0. Aka, first official release on the apstore..

### PR DESCRIPTION
**Pull request by matiasdelellis**
### Added
- Experimental support of External Storage. Issue #212
- Add some documentation about how expect to install, test and use the application
- Optionally you can install Pdlib 1.0.2 from https://github.com/matiasdelellis/pdlib that increase the speed of clustering drastically.
- The sidebar has been rewritten to show it in the Photos application.
- Add php-bzip2 as a necessary dependency to install the models.

### Changed
- Also adds a minimum php memory requirement for HOG. 128 MB.
. Indicate which model is enabled in the summary table of the setup --model command.

### Bug fixes
- Consider the memory configured in php as a dependency on the models.
- Improves the description of errors and prints the links to documentation whenever it can.
- Fix plurals in admin panel. Issue #256.
- Use paginated queries when search persons on file app. Fix part of issue #263.
- Search mainly faces, rather than persons in file view. Fix issue #264.
- Don't compare a good face with a bad one. This greatly improves the quality of the faces clusters.
- Fix that sidebar says no faces were found when just not clustered yet. Issue #255.
- Fix tests on Nextcloud 18 and 19.

### Translations
- New French tranlation thanks to Florian Carpentier
- Update Chinese translation thanks to yui874397188
- Update German translation thanks to Johannes Szeibert
- Update Polish translation thanks to Piotr Esse
- Update Spanish translation thanks to Matias De lellis

### CODE REVIEW

**Comment by matiasdelellis** [comment]
@stalker314314 
I hope your :+1:. Any other comment?

**Comment by stalker314314** [comment]
You get  👍👍👍  and happy first official release!!!:)

**Comment by matiasdelellis** [comment]
:smile::clap: :tada: :beers:

**Comment by Piyush-Bijwal** [comment]
Hi Team,

i'm new to this. i have installed Nextcloud on ubuntu and it's running good. When i tried to download and enable i'm getting error "App "Face Recognition" cannot be installed because the following dependencies are not fulfilled: The library bz2 is not available.". I checked and installed sudo apt-get install libbz2-dev php7.4-bz2 but still it's not working.

I'm not sure whether this is right place to raise this issue.

**Comment by matiasdelellis** [comment]
@Piyush-Bijwal 
You installed in ubuntu focal? Any other external repository?

Test php version and if it is installed:
```
[matias@ideapad ~]$ php -v
PHP 7.4.6 (cli) (built: May 12 2020 08:09:15) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

[matias@ideapad ~]$ php -m | grep bz2
bz2
```

You can try to restart php and try again.
> sudo systemctl status php7.4-fpm.service

**Comment by Piyush-Bijwal** [comment]
Thanks @matiasdelellis , restart of php worked.

**Pull request merged**
