### PR TITLE
Add Czech localization

### PR DESCRIPTION
**Pull request by p-bo**

### CODE REVIEW

**Comment by matiasdelellis** [comment]
Hi @p-bo
Thank you for taking the job, but we manage the translations at transifex..

* https://www.transifex.com/matias/nextcloud-facerecognition

Can you participate there? 😄

**Comment by p-bo** [comment]
Hi @matiasdelellis
yes, for sure - may I ask you to confirm request for new language in Transifex project please (and ideally assign me to that team)?
Thanks :-)

**Comment by matiasdelellis** [comment]
> Hi @matiasdelellis
> yes, for sure - may I ask you to confirm request for new language in Transifex project please (and ideally assign me to that team)?
> Thanks :-)

Accept the language, now you must request its translation. I can't add you without your email.

Thanos😃

**Comment by p-bo** [comment]
Hi @matiasdelellis
Thanks for accepting language, requested to join newly created Czech team - may I ask you to accept this request too please?

Thanks :-)

**Comment by matiasdelellis** [comment]
Done,

**Comment by p-bo** [comment]
Thanks, translation done too and added watching for update of source strings for myself to keep it translated in future too :-) Closing this.

**Pull request closed without merging**
