### PR TITLE
Allow Setting a Custom Model Path. Replaces #390

### PR DESCRIPTION
**Pull request by matiasdelellis**
Thanks you so much @hahagu

### CODE REVIEW

**Comment by hahagu** [comment]
> Thanks you so much @hahagu

I think it caused you more trouble than doing it yourself 😅
Thanks for helping!
I've really only provided the idea for it :)

**Comment by mgutschmidt** [comment]
Hi, can you describe how to use this Setting? I also use S3 Storage, but can't figure out to get this solution running...

**Comment by hahagu** [comment]
> Hi, can you describe how to use this Setting? I also use S3 Storage, but can't figure out to get this solution running...

https://github.com/matiasdelellis/facerecognition/blob/9b4ebc9e8eab169444653c90d87237a8ce2b4561/lib/Service/SettingsService.php#L133

**Comment by mgutschmidt** [comment]
Ahh, too simple^^. It worked, thanks!

**Pull request merged**
