### PR TITLE
Let's try NC18 and php 7.3

### PR DESCRIPTION
**Pull request by matiasdelellis**

### CODE REVIEW

**Comment by matiasdelellis** [comment]
Let's see the results to see what happens .. :confused:

**Comment by DrRSatzteil** [comment]
Just to give you a little bit of my experience: I'm running this App on NC 18.3 with PHP 7.3 and had no problems so far.

**Comment by matiasdelellis** [comment]
Hi
I also have NC18 installed without problems, however, I can't stop testing just because it works for me.. Here the problem seems that NC18 need PHPUnit8 which is incompatible with the other PHPUnit test.

Thanks!

**Comment by matiasdelellis** [comment]
Close in favor of https://github.com/matiasdelellis/facerecognition/pull/269

**Pull request closed without merging**
