### PR TITLE
Update translations from transifex

### PR DESCRIPTION
**Pull request by matiasdelellis**
Update spanish and bring first version of Serbian language..

### CODE REVIEW

**Comment by matiasdelellis** [comment]
p.s: Try to complete your language and suggest any English modification.. :wink:

**Comment by stalker314314** [comment]
Done with Serbian. I found some typos and wrote them as "issues" on Transifex, but I am not sure did you receive any notification from Transifex around this? If you did not, let me know!

**Comment by stalker314314** [comment]
BTW, when doing PR for transifex, don't wait for my approval, just pull:P

**Comment by matiasdelellis** [comment]
> Done with Serbian. I found some typos and wrote them as "issues" on Transifex, but I am not sure did you receive any notification from Transifex around this? If you did not, let me know!

Great.. Now I check them. :smiley:

**Comment by matiasdelellis** [comment]
@stalker314314 

Except "More sensitivity, more groups" the rest fixed..  When you finish translating these new strings again, I will merge it. :wink: 

> BTW, when doing PR for transifex, don't wait for my approval, just pull:P

I want to avoid many PR/commits for translations. haha.. :man_facepalming: :sweat_smile:

p.s: Luckily I get all the notifications.. so, we can trust them.

**Comment by stalker314314** [comment]
I finished:)

**Comment by matiasdelellis** [comment]
> I finished:)

Transifex does not reinterpret string fixes .. You will have to translate them again .. :sweat_smile:

**Comment by stalker314314** [comment]
done now:)

**Comment by matiasdelellis** [comment]
Great ..
Now you can enjoy the application with your native language. :smile:

**Pull request merged**
